# Use an official Node.js 18 runtime as a parent image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Install system dependencies (required for some npm packages)

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Install nodemon globally
RUN npm install -g nodemon

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 8012

# Set environment variables from .env file
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
COPY .env .env

# Run Prisma generate to create the client
RUN npx prisma generate

# Define the command to run your app with nodemon
CMD ["nodemon", "app.js"]
